IMAGE_NAME = "generic/ubuntu2204" # Image a utiliser : Ubuntu 22.04 (Jammy)
MEM = 2048                        # Quantite de RAM a configurer
CPU = 2                           # Quantite de CPU a configurer
NB_MASTER = 1                     # Nombre de master a creer (/!\ inferieur ou egal à 9)
NB_WORKER = 3                     # Nombre de workers a creer
NODE_NETWORK_BASE = "192.168.10"  # Reseau a utiliser pour les VM
MASTER_START_IP = 20              # Premiere adresse IP pour le(s) master(s)
WORKER_START_IP = 30              # Premiere adresse IP pour le(s) worker(s)
POD_NETWORK = "10.0.0.0/16"       # Reseau pour la communication entre pods

# Construction du fichier Host
hosts_text = "192.168.10.10  ansible-controlle\n"           # Ajout du controller ansible
NB_MASTER.times do |i|                                      # Ajout des noeuds Master
  ip_address = "#{NODE_NETWORK_BASE}.#{MASTER_START_IP+i}"
  hosts_text += "#{ip_address}  master-#{i+1}\n"
end
NB_WORKER.times do |i|                                      # Ajout des noeuds Worker
  ip_address = "#{NODE_NETWORK_BASE}.#{WORKER_START_IP+i}"
  hosts_text += "#{ip_address}  worker-#{i+1}\n"
end



Vagrant.configure("2") do |config|

  # Definition de la RAM & du CPU
  config.vm.provider "vmware_desktop" do |perf|
    perf.memory = MEM
    perf.cpus = CPU
  end

  # Configuration d'une VM Ansible
  config.vm.define "ansible-controller" do |ansible|

    # Image, reseau et nom d'hote
    ansible.vm.box = IMAGE_NAME
    ansible.vm.network "private_network", ip: "#{NODE_NETWORK_BASE}.10"
    ansible.vm.hostname = "ansible-controller"
    ansible.vm.provision "shell", inline: <<-SHELL
      echo "#{hosts_text}" | sudo tee -a /etc/hosts #> /dev/null
    SHELL

    # Installation et configuration Ansible
    ansible.vm.provision "shell", privileged: false, path: "install_ansible.sh"
    ansible.vm.synced_folder "roles", "/ansible/roles"
  end

  # Configuration du/des master(s)
  (1..NB_MASTER).each do |i|
    config.vm.define "master-#{i}" do |master|

      # Image, reseau et nom d'hote
      master.vm.box = IMAGE_NAME
      master.vm.network "private_network", ip: "#{NODE_NETWORK_BASE}.#{19+i}"
      master.vm.hostname = "master-#{i}"
      master.vm.provision "shell", inline: <<-SHELL
        echo "#{hosts_text}" | sudo tee -a /etc/hosts #> /dev/null
      SHELL
    end
  end

  # Configuration du/des worker(s)
  (1..NB_WORKER).each do |i|
    config.vm.define "worker-#{i}" do |worker|

      # Image, reseau et nom d'hote
      worker.vm.box = IMAGE_NAME
      worker.vm.network "private_network", ip: "#{NODE_NETWORK_BASE}.#{29+i}"
      worker.vm.hostname = "worker-#{i}"
      worker.vm.provision "shell", inline: <<-SHELL
        echo "#{hosts_text}" | sudo tee -a /etc/hosts #> /dev/null
      SHELL
      
    end
  end

end
