- name: Suppression du fichier /etc/containerd/config.toml
  ansible.builtin.file:
    path: /etc/containerd/config.toml
    state: absent
  # notify:
  # - restart containerd
  # > Ne fonctionne pas, donc ajout de la tâche dans le main.yml

- name: restart containerd
  ansible.builtin.service:
    name: containerd
    state: restarted

- name: Initialise le cluster Kubernetes avec kubeadm
  become: true
  command: kubeadm init --apiserver-advertise-address="{{ node_ip }}" --apiserver-cert-extra-sans="{{ node_ip }}" --node-name="{{ node_name }}" --pod-network-cidr={{ pod_network }}

- name: Configuration de Kubeconfig pour l'utilisateur vagrant
  command: "{{ item }}"
  with_items:
  - mkdir -p /home/vagrant/.kube
  - cp -i /etc/kubernetes/admin.conf /home/vagrant/.kube/config
  - chown vagrant:vagrant /home/vagrant/.kube/config

# - name: Installation du CNI Flannel
#   become: false
#   command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml

# - name: Generation de la commande de join
#   command: kubeadm token create --print-join-command
#   register: join_command

# - name: Copie de la commande de join dans un fichier local
#   become: false
#   local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"