gpg_keys:
- key: https://download.docker.com/linux/ubuntu/gpg
- key: https://packages.cloud.google.com/apt/doc/apt-key.gpg

repositories:
- repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable"
- repo: "deb https://apt.kubernetes.io/ kubernetes-xenial main"

https_packages:
- name: apt-transport-https
- name: curl

docker_packages:
- name: docker-ce
- name: docker-ce-cli 
- name: containerd.io

k8s_packages:
- name: kubelet=1.26.4-00
- name: kubectl=1.26.4-00
- name: kubeadm=1.26.4-00
